// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

public final class Msg {
  private Msg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface controlMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 can_address = 1;
    /**
     * <code>required int32 can_address = 1;</code>
     */
    boolean hasCanAddress();
    /**
     * <code>required int32 can_address = 1;</code>
     */
    int getCanAddress();

    // repeated bytes can_payload = 2;
    /**
     * <code>repeated bytes can_payload = 2;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getCanPayloadList();
    /**
     * <code>repeated bytes can_payload = 2;</code>
     */
    int getCanPayloadCount();
    /**
     * <code>repeated bytes can_payload = 2;</code>
     */
    com.google.protobuf.ByteString getCanPayload(int index);
  }
  /**
   * Protobuf type {@code controlMessage}
   */
  public static final class controlMessage extends
      com.google.protobuf.GeneratedMessage
      implements controlMessageOrBuilder {
    // Use controlMessage.newBuilder() to construct.
    private controlMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private controlMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final controlMessage defaultInstance;
    public static controlMessage getDefaultInstance() {
      return defaultInstance;
    }

    public controlMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private controlMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              canAddress_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                canPayload_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000002;
              }
              canPayload_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          canPayload_ = java.util.Collections.unmodifiableList(canPayload_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Msg.internal_static_controlMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Msg.internal_static_controlMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Msg.controlMessage.class, Msg.controlMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<controlMessage> PARSER =
        new com.google.protobuf.AbstractParser<controlMessage>() {
      public controlMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new controlMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<controlMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 can_address = 1;
    public static final int CAN_ADDRESS_FIELD_NUMBER = 1;
    private int canAddress_;
    /**
     * <code>required int32 can_address = 1;</code>
     */
    public boolean hasCanAddress() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 can_address = 1;</code>
     */
    public int getCanAddress() {
      return canAddress_;
    }

    // repeated bytes can_payload = 2;
    public static final int CAN_PAYLOAD_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> canPayload_;
    /**
     * <code>repeated bytes can_payload = 2;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getCanPayloadList() {
      return canPayload_;
    }
    /**
     * <code>repeated bytes can_payload = 2;</code>
     */
    public int getCanPayloadCount() {
      return canPayload_.size();
    }
    /**
     * <code>repeated bytes can_payload = 2;</code>
     */
    public com.google.protobuf.ByteString getCanPayload(int index) {
      return canPayload_.get(index);
    }

    private void initFields() {
      canAddress_ = 0;
      canPayload_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCanAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, canAddress_);
      }
      for (int i = 0; i < canPayload_.size(); i++) {
        output.writeBytes(2, canPayload_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, canAddress_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < canPayload_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(canPayload_.get(i));
        }
        size += dataSize;
        size += 1 * getCanPayloadList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Msg.controlMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Msg.controlMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Msg.controlMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Msg.controlMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Msg.controlMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Msg.controlMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Msg.controlMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Msg.controlMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Msg.controlMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Msg.controlMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Msg.controlMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code controlMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Msg.controlMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Msg.internal_static_controlMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Msg.internal_static_controlMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Msg.controlMessage.class, Msg.controlMessage.Builder.class);
      }

      // Construct using Msg.controlMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        canAddress_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        canPayload_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Msg.internal_static_controlMessage_descriptor;
      }

      public Msg.controlMessage getDefaultInstanceForType() {
        return Msg.controlMessage.getDefaultInstance();
      }

      public Msg.controlMessage build() {
        Msg.controlMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Msg.controlMessage buildPartial() {
        Msg.controlMessage result = new Msg.controlMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.canAddress_ = canAddress_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          canPayload_ = java.util.Collections.unmodifiableList(canPayload_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.canPayload_ = canPayload_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Msg.controlMessage) {
          return mergeFrom((Msg.controlMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Msg.controlMessage other) {
        if (other == Msg.controlMessage.getDefaultInstance()) return this;
        if (other.hasCanAddress()) {
          setCanAddress(other.getCanAddress());
        }
        if (!other.canPayload_.isEmpty()) {
          if (canPayload_.isEmpty()) {
            canPayload_ = other.canPayload_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureCanPayloadIsMutable();
            canPayload_.addAll(other.canPayload_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCanAddress()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Msg.controlMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Msg.controlMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 can_address = 1;
      private int canAddress_ ;
      /**
       * <code>required int32 can_address = 1;</code>
       */
      public boolean hasCanAddress() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 can_address = 1;</code>
       */
      public int getCanAddress() {
        return canAddress_;
      }
      /**
       * <code>required int32 can_address = 1;</code>
       */
      public Builder setCanAddress(int value) {
        bitField0_ |= 0x00000001;
        canAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 can_address = 1;</code>
       */
      public Builder clearCanAddress() {
        bitField0_ = (bitField0_ & ~0x00000001);
        canAddress_ = 0;
        onChanged();
        return this;
      }

      // repeated bytes can_payload = 2;
      private java.util.List<com.google.protobuf.ByteString> canPayload_ = java.util.Collections.emptyList();
      private void ensureCanPayloadIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          canPayload_ = new java.util.ArrayList<com.google.protobuf.ByteString>(canPayload_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated bytes can_payload = 2;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getCanPayloadList() {
        return java.util.Collections.unmodifiableList(canPayload_);
      }
      /**
       * <code>repeated bytes can_payload = 2;</code>
       */
      public int getCanPayloadCount() {
        return canPayload_.size();
      }
      /**
       * <code>repeated bytes can_payload = 2;</code>
       */
      public com.google.protobuf.ByteString getCanPayload(int index) {
        return canPayload_.get(index);
      }
      /**
       * <code>repeated bytes can_payload = 2;</code>
       */
      public Builder setCanPayload(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCanPayloadIsMutable();
        canPayload_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes can_payload = 2;</code>
       */
      public Builder addCanPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCanPayloadIsMutable();
        canPayload_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes can_payload = 2;</code>
       */
      public Builder addAllCanPayload(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureCanPayloadIsMutable();
        super.addAll(values, canPayload_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes can_payload = 2;</code>
       */
      public Builder clearCanPayload() {
        canPayload_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:controlMessage)
    }

    static {
      defaultInstance = new controlMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:controlMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_controlMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_controlMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmsg.proto\":\n\016controlMessage\022\023\n\013can_add" +
      "ress\030\001 \002(\005\022\023\n\013can_payload\030\002 \003(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_controlMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_controlMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_controlMessage_descriptor,
              new java.lang.String[] { "CanAddress", "CanPayload", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
