/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Mon Oct  3 14:06:09 2016. */

#include "msg.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t controlMessage_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, controlMessage, can_address, can_address, 0),
    PB_FIELD(  2, BYTES   , REPEATED, STATIC  , OTHER, controlMessage, can_payload, can_address, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
